AWSTemplateFormatVersion: 2010-09-09
Description: Maintenance server deployment
Parameters:
  AMI:
    Description: Always use the latest CentOS or Amazon Linux 2 imagefactory image.
    Type: String
  ArchPath:
    Type: String
    Default: DX.DE
  Creator:
    AllowedPattern: .+
    Default: scheel
    Type: String
  Customer:
    Type: String
    Default: DE.Internal
  Env:
    AllowedPattern: .+
    Type: String
  HostName:
    Default: Maintenance Server
    Type: String
  InstanceType:
    Default: t3.medium
    Type: String
  KeyName:
    Default: ea-keypair
    Type: String
  Owner:
    Default: ea-devops@adobe.com
    Type: String
  PublicKey:
    Default: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9CzPqiWDvZFg5Po32VYjUFmHjulAawKRfzTryMtQfIW7jnoyhmKw6Y9BLlb5jzU5zG/JiBfLQ9uWvKjJyPZct0Bqkr2I/hS9mS9mBT7VcicxF4DAEwraeHHucgtyzjwVjhC7S9u2eNCnQC+HUxUqCzmYdx0HuN8pg4tXEm7wYRTia347s2cOFQIErtmpWG30oU3B7gbW0eNV+px4FhNwkh1t98SwBG4ubSGIhbtBDPcDhM1xKkMVaM7HX4Xhco9g4Bb9FVl/zavGGRixgeyHahpg1lZW3TWcmiI0q3HYLRXxdXzw9VekXK6KHphIAzHgMsTddDMmLhfHvzW1L2z6Dp5DMoLcoEXmaY/onhIX7XU3rwabj5BG+wTbeZtYwLNajH4OmpilFTfCMhQSaeOud6/8Wc8BAvo3WfFUbhlhfhaYsrm2sKKmHm0U+xa6fccd3A1yCmP2sCgxS5u8494XSPRaSMThNwGE2riYJsa820YIfdN846lPchCF3wbL+LLVIWRwZRXGOm1bf9ufcfx6d6bpg2mg6k7zHTDqY5VrSe6kunUUy+Fz3sDQCEL7eSVaW7XjPvpt/lqu72H7kEkOhTY3bgAgGM2B/23j4mbkfjLQGWeWnGaMF6CumXJr7wtkWS16uyB3Ms/BMPHkCqrvORhTDb0hU31gYQRnKGJY3Pw== ea_devops@adobe.com"
    Type: String
  SubnetId:
    Description: Subnet ID where the instance will live.
    Type: String
  UserName:
    Default: devops
    Type: String
Resources:
  Instance:
    Properties:
      #BlockDeviceMappings: []
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 1000
            DeleteOnTermination: false
      ImageId: !Ref 'AMI'
      InstanceType: !Ref 'InstanceType'
      KeyName: de-devops
      SecurityGroupIds:
        - !ImportValue 'AdobeVPCPublicSG'
      SubnetId: !Ref 'SubnetId'
      Tags:
        - Key: Name
          Value: !Ref 'HostName'
        - Key: Adobe.Owner
          Value: ea_devops@adobe.com
        - Key: Adobe.Customer
          Value: !Ref 'Customer'
        - Key: Adobe.ArchPath
          Value: !Ref 'ArchPath'
        - Key: Adobe.EA.Creator
          Value: !Ref 'Creator'
        - Key: Adobe.Environment
          Value: !Ref 'Env'
        - Key: CMDB_device_service
          Value: Consulting - VA6 - dev
        - Key: CMDB_environment
          Value: Consulting Engineering Services - AWS - ec2
      # UserData:
      #   Fn::Base64: !Sub |
      #     #!/usr/bin/env bash
      #     adduser ${UserName}
      #     usermod -a -G sudo ${UserName}
      #     mkdir ~${UserName}/.ssh
      #     touch ~${UserName}/.ssh/authorized_keys
      #     chmod -R u=rwX,go-rwx ~${UserName}/.ssh
      #     chown -R ${UserName}: ~${UserName}/.ssh
      #     echo "${PublicKey}" >> ~${UserName}/.ssh/authorized_keys
      #     echo "${UserName} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/ea
      #     echo "Defaults:${UserName} !requiretty" >> /etc/sudoers.d/ea
      #     passwd --delete ${UserName}
    Type: AWS::EC2::Instance
Outputs:
  ServerIP:
    Description: The IP address of the server.
    Value: !GetAtt Instance.PrivateIp
