---
- hosts: amazon_linux
  tasks:
    - name: Copy repo file
      copy:
        src: /tmp/if_hardener/imagefactory_amazon_linux.repo
        dest: /etc/yum.repos.d/imagefactory.repo
        mode: '600'
        owner: root
        group: root
      become: yes
    - name: install amazon-linux-extras
      command: amazon-linux-extras install -y epel
      become: yes
    - name: Install hardener (if-hardener-amazon-linux)
      yum:
        state: installed
        name: if-hardener-amazon-linux, pwgen
      become: yes
- hosts: amazon_linux_2
  tasks:
    - name: Copy repo file
      copy:
        src: /tmp/if_hardener/imagefactory_amazon_linux_2.repo
        dest: /etc/yum.repos.d/imagefactory.repo
        mode: '600'
        owner: root
        group: root
      become: yes
    - name: install amazon-linux-extras
      command: amazon-linux-extras install -y epel
      become: yes
    - name: Install hardener (if-hardener-amazon-linux-2)
      yum:
        state: installed
        name: if-hardener-amazon-linux-2, pwgen
      become: yes
- hosts: centos7
  tasks:
    - name: Copy repo file
      copy:
        src: /tmp/if_hardener/imagefactory_centos7.repo
        dest: /etc/yum.repos.d/imagefactory.repo
        mode: '600'
        owner: root
        group: root
      become: yes
    - name: Install hardener (if-hardener-amazon-centos7)
      yum:
        state: installed
        name: if-hardener-centos-7, pwgen
      become: yes
- hosts: centos8
  tasks:
    - name: Copy repo file
      copy:
        src: /tmp/if_hardener/imagefactory_centos8.repo
        dest: /etc/yum.repos.d/imagefactory.repo
        mode: '600'
        owner: root
        group: root
      become: yes
    - name: Install hardener (if-hardener-amazon-centos8)
      yum:
        state: installed
        name: if-hardener-centos-8, pwgen
      become: yes
- hosts: all
  tasks:
    - name: Copy skip checks file
      copy:
        src: skip-checks-file.yml
        dest: /root/skip-checks-file.yml
        mode: '644'
        owner: root
        group: root
      become: yes
    - name: Copy image hardener script
      copy:
        src: harden.sh
        dest: /home/de/harden.sh
        mode: '700'
        owner: root
        group: root
      become: yes
    - name: Harden image.
      script: harden.sh
      become: yes
