hosts:
  - Host: '*'
    StrictHostKeyChecking: 'no'
    LogLevel: QUIET
  - Host: 'jump.*.ea.adobe.net'
    User: ea
    IdentityFile: ~/.ssh/id_rsa_ea
  - Host: '10.*'
    IdentityFile: ~/.ssh/id_rsa_devops
    User: ec2-user
  - Host:
      - gitcorp.adobe.net
      - git.corp.adobe.com
    Hostname: gitcorp.adobe.net
    User: git
    IdentityFile: ~/.ssh/id_rsa_git
