---
- hosts: amazon_linux:centos6
  tasks:
    - name: Install python3
      yum:
        name: python36
        state: installed
      become: yes
- hosts: amazon_linux_2:centos7
  tasks:
    - name: Install python3
      yum:
        name: python3
        state: installed
      become: yes
- hosts: all
  tasks:
    - name: Install pip3
      script: install_pip3.sh
      become: yes
    - name: Install python3 requests
      pip:
        executable: /usr/local/bin/pip3
        name: requests
        state: latest
      become: yes
    - name: Execute IDM Script
      script: config_idm_for_imagefactory_images.py
      become: yes
      environment:
        IDM_LDAP_SIMPLE: "{{ lookup('env', 'IDM_LDAP_SIMPLE') }}"
        IDM_LDAP_SUDO: "{{ lookup('env', 'IDM_LDAP_SIMPLE') }}"
    - name: Restart sssd
      service:
        name: sssd
        state: restarted
      become: yes
