---
# This tests for python 3 and installs it if necessary
- hosts: hosted
  gather_facts: false
  
  tasks:
  - name: install python 3
    raw: test -e /usr/bin/python3 || yum install python3
    register: out
  # - debug: msg="STDOUT - {{ out.stdout }}"
  # - debug: msg="STDERR - {{ out.stderr }}"

  # - name: install latest pip3
  #   raw: test -e /usr/local/bin/pip3 || (curl https://bootstrap.pypa.io/get-pip.py | python3)
  #   register: out
  # - debug: msg="STDOUT - {{ out.stdout }}"
  # - debug: msg="STDERR - {{ out.stderr }}"

  # - name: install latest pyyaml library using pip3
  #   pip:
  #     name: pyyaml
  #     state: present
  
  - name: Copy include/excludes to destination
    copy:
      src: DAKCSShot_files.json
      dest: /tmp/DAKCSShot_files.json
      follow: yes
      force: yes
      mode: '600'

  - name: Run script
    script: dakcsshot/DAKCSShot.py
    args:
      executable: python3
    register: out
  - debug: msg="STDOUT - {{ out.stdout }}"
  - debug: msg="STDERR - {{ out.stderr }}"

  - name: Get list of remote database files
    shell: find /tmp -maxdepth 1 -type f -name "DAKCSShot.*.zip"
    register: files_to_retrieve

  - name: Retrieve remote database files
    fetch:
      src: "{{ item }}"
      dest: db_store/
      flat: yes
    with_items: "{{ files_to_retrieve.stdout_lines }}"
  
  # - name: Delete remote database files
  #   file:
  #     path: "{{ item }}"
  #     state: absent
  #   with_items: "{{ files_to_retrieve.stdout_lines }}"

